<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <OutputType>Library</OutputType>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <!-- Instructs MSBuild to completely bypass looking at local framework caches -->
    <AddFrameworkPaths>false</AddFrameworkPaths>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>libs\Assembly-CSharp.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="ColossalManaged">
      <HintPath>libs\ColossalManaged.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="ICities">
      <HintPath>libs\ICities.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>libs\UnityEngine.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>libs\UnityEngine.UI.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="ColossalFramework">
      <HintPath>libs\ColossalFramework.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>
</Project>
