<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <OutputType>Library</OutputType>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <!-- Explicitly forces MSBuild to look into your local libs directory -->
    <ReferencePath>$(MSBuildProjectDirectory)\libs;$(ReferencePath)</ReferencePath>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp" HintPath="libs\Assembly-CSharp.dll" Private="False" />
    <Reference Include="ColossalManaged" HintPath="libs\ColossalManaged.dll" Private="False" />
    <Reference Include="ICities" HintPath="libs\ICities.dll" Private="False" />
    <Reference Include="UnityEngine" HintPath="libs\UnityEngine.dll" Private="False" />
    <Reference Include="UnityEngine.UI" HintPath="libs\UnityEngine.UI.dll" Private="False" />
  </ItemGroup>
</Project>
