name: Build Cities Skylines Mod

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    # We use msbuild to do both the restore pass and compilation at once safely
    - name: Build Mod
      run: msbuild JonShift.csproj /t:Restore;Build /p:Configuration=Release
